/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package javapracticegame;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Hashtable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;


/**
 *
 * @author Landen
 */
public class MainGame extends javax.swing.JFrame {

    
    public MainGame() {
//        try {
//            //new File("./slccLogoBW.png")
//            BufferedImage logo = ImageIO.read(this.getClass().getResource("slccLogoBW.png"));
//            
//        } catch (IOException ex) {
//            Logger.getLogger(MainGame.class.getName()).log(Level.SEVERE, null, ex);
//        }
        initComponents();
        
        //        Color manilla = new Color(255,238,198);
            //        Color gold = new Color(238,178,17);
            //        bgMain.setBackground(manilla);
            //        jLabel1.setFont(new Font("Helvetica Neue", Font.BOLD, 25));
            //        jLabel1.setAlignmentX(JLabel.CENTER);
            //        jLabel2.setFont(new Font("Helvetica Neue", Font.BOLD, 25));
            //        jLabel2.setAlignmentX(JLabel.CENTER);
            //        jSlider2.setAlignmentX(JSlider.CENTER);
            //
            //        button1.setBackground(manilla);
            //        button1.setForeground(gold);
            //        button1.setFont(new Font("Helvetica Neue", Font.BOLD, 12));
            //
            //        button2.setBackground(manilla);
            //        button2.setForeground(gold);
            //        button2.setFont(new Font("Helvetica Neue", Font.BOLD, 12));
            //        jSlider2.setFont(new Font("Helvetica Neue", Font.BOLD, 15));
            //        jSlider2.setFont(new Font("Helvetica Neue", Font.BOLD, 15));//        Color manilla = new Color(255,238,198);
            //        Color gold = new Color(238,178,17);
            //        bgMain.setBackground(manilla);
            //        jLabel1.setFont(new Font("Helvetica Neue", Font.BOLD, 25));
            //        jLabel1.setAlignmentX(JLabel.CENTER);
            //        jLabel2.setFont(new Font("Helvetica Neue", Font.BOLD, 25));
            //        jLabel2.setAlignmentX(JLabel.CENTER);
            //        jSlider2.setAlignmentX(JSlider.CENTER);
            //
            //        button1.setBackground(manilla);
            //        button1.setForeground(gold);
            //        button1.setFont(new Font("Helvetica Neue", Font.BOLD, 12));
            //
            //        button2.setBackground(manilla);
            //        button2.setForeground(gold);
            //        button2.setFont(new Font("Helvetica Neue", Font.BOLD, 12));
            //        jSlider2.setFont(new Font("Helvetica Neue", Font.BOLD, 15));
            //        jSlider2.setFont(new Font("Helvetica Neue", Font.BOLD, 15));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgMain = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        button1 = new java.awt.Button();
        button2 = new java.awt.Button();
        jSlider2 = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgMain.setBackground(new java.awt.Color(255, 238, 198));
        bgMain.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(238, 178, 17)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapracticegame/slccLogoSmall.png"))); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        button1.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        button1.setLabel("Start Game");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        button2.setFont(new java.awt.Font("Helvetica Neue", 0, 13)); // NOI18N
        button2.setLabel("Exit Game");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });

        jSlider2.setBackground(new java.awt.Color(255, 238, 198));
        jSlider2.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        jSlider2.setMajorTickSpacing(1);
        jSlider2.setMaximum(3);
        Hashtable labelTable = new Hashtable();
        labelTable.put(new Integer(0), new JLabel("Level 1"));
        labelTable.put(new Integer(1), new JLabel("Level 2"));
        labelTable.put(new Integer(2), new JLabel("Level 3"));
        labelTable.put(new Integer(3), new JLabel("Level 4"));
        jSlider2.setLabelTable(labelTable);
        System.out.println(jSlider2.getValue());
        jSlider2.setPaintLabels(true);
        jSlider2.setPaintTicks(true);
        jSlider2.setSnapToTicks(true);
        jSlider2.setValue(0);
        jSlider2.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSlider2PropertyChange(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 25)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Level");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Java Practice");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout bgMainLayout = new org.jdesktop.layout.GroupLayout(bgMain);
        bgMain.setLayout(bgMainLayout);
        bgMainLayout.setHorizontalGroup(
            bgMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bgMainLayout.createSequentialGroup()
                .add(38, 38, 38)
                .add(button2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(38, 38, 38))
            .add(bgMainLayout.createSequentialGroup()
                .add(bgMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bgMainLayout.createSequentialGroup()
                        .add(197, 197, 197)
                        .add(jLabel1))
                    .add(bgMainLayout.createSequentialGroup()
                        .add(137, 137, 137)
                        .add(jSlider2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(bgMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, bgMainLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .add(jLabel2)
                .add(59, 59, 59))
        );
        bgMainLayout.setVerticalGroup(
            bgMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, bgMainLayout.createSequentialGroup()
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 57, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(47, 47, 47)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 100, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSlider2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(bgMainLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(button1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(button2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, bgMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bgMain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
<<<<<<< .mine
<<<<<<< .mine
    

=======
    
>>>>>>> .r49
    public  int read highscore ( )  { 
        SharedPreferences pref = getSharedPreferences ( "GAME" , 0 ) ; 
        return pref. getInt ( "HIGH SCORE" , 0 ) ; 
    }

    	
 
    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        problemGUI gameStart = new problemGUI(jSlider2.getValue());       
        bgMain.setVisible(false);
        this.remove(bgMain);
        this.add(gameStart, BorderLayout.CENTER);
        gameStart.setQuestion();
        gameStart.setVisible(true);  
        
        
    }//GEN-LAST:event_button1ActionPerformed
=======

    private void jSlider2PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSlider2PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_jSlider2PropertyChange
>>>>>>> .r61

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button2ActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        problemGUI gameStart = new problemGUI(jSlider2.getValue());
        bgMain.setVisible(false);
        this.remove(bgMain);
        this.add(gameStart, BorderLayout.CENTER);
        gameStart.setQuestion();
        gameStart.setVisible(true);

    }//GEN-LAST:event_button1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgMain;
    private java.awt.Button button1;
    private java.awt.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSlider jSlider2;
    // End of variables declaration//GEN-END:variables
    
    
}
